# Generated by Django 5.0.14 on 2025-08-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_module', '0002_alter_order_customer_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Order_Number',
            field=models.IntegerField(unique=True),
        ),
    ]
