# Generated by Django 5.2.4 on 2025-08-02 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_module', '0003_alter_order_order_number'),
        ('inventory_module', '0003_inventory_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Order_date',
            new_name='order_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Order_Info',
            new_name='order_info',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Order_Number',
            new_name='order_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Customer',
        ),
        migrations.AddField(
            model_name='order',
            name='inventory_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='inventory_module.inventory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
