# Generated by Django 5.2.4 on 2025-07-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_module", "0002_inventory_coil_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="status",
            field=models.CharField(
                choices=[
                    ("To be created", "To be created"),
                    ("Created", "Created"),
                    ("Shipped", "Shipped"),
                ],
                default="To be created",
                max_length=20,
            ),
        ),
    ]
