# Generated by Django 5.2.4 on 2025-08-02 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_module', '0006_alter_order_customer_alter_order_customer_name'),
        ('inventory_module', '0003_inventory_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='Order_Number',
        ),
        migrations.AddField(
            model_name='inventory',
            name='order_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='customer_module.order'),
        ),
    ]
