# Generated by Django 5.2.4 on 2025-08-02 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_module', '0004_remove_inventory_order_number_inventory_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='order_number',
        ),
    ]
